title: Xin Cynthia Tong
url: "https://tongxin97.github.io"
baseurl: ""

favicon: true
favicon_location: "media/favicon.ico"
is_contact: false

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://tongxin97.github.io"
footer_text: "Xin Cynthia Tong &copy; 2019"

sass:
  style: compressed
  sass_dir: _sass

nav:
 - name: "Home"
   link: "index"
 - name: "Resume"
   link: "./media/Xin_Cynthia_Tong_Resume.pdf"
#  - name: "Blog"
#    link: "/blog"
 - name: "Contact"
   link: "contact"
